# select a language.

# Japanese            => jpn
# English             => eng
# Chinese-Simplified  => chs
# German              => deu
# Chinese-Traditional => zho
# Portugues           => por
# Korean              => kor
language: eng



# key item setting
keyitem-id: 288
keyitem-meta: 0
